version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    image: sanjaysify/vite-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://10.0.2.16/api/v1
  backend:
    build:
      context: ./backend
    image: sanjaysify/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      domain: http://172.16.20.110/kubecost
