version: "3.8"

services:
  frontend:
    # build:
    #   context: ./frontend
    image: sanjaysify/vite-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://1.7.187.117/api/v1

  backend:
    # build:
    #   context: ./backend_inProgress
    image: sanjaysify/backend:latest
    ports:
      - "8000:8000"
      - "5432:5432" # expose Postgres
    volumes:
      - ./backend:/app
      - postgres_data:/var/lib/postgresql/data # persist Postgres data
    env_file:
      - ./backend/.env # load env vars from .env file
    stdin_open: true
    tty: true

volumes:
  postgres_data:
