version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kubermets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    # build:
    #   context: ./backend_inProgress
    image: sanjaysify/backend:latest
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    # build:
    #   context: ./frontend
    image: sanjaysify/vite-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
