swagger: "2.0"
info:
  title: Kubernetes metrics explorer
  description: All API's related to the metrics.
  version: "0.0.0"
host: localhost:8080
basePath: /
schemes:
  - http
tags:
  - name: health
    description: Health-related endpoints
  - name: default
    description: Default API responses
paths:
  /:
    get:
      tags:
        - default
      summary: Returns the default response from the API.
      responses:
        200:
          description: The default response
          schema:
            type: string

  /health:
    get:
      tags:
        - health
      summary: Health check
      responses:
        200:
          description: OK
          schema:
            type: string

  /custom:
    post:
      tags:
        - default
      summary: Accepts a JSON with `say_hello`
      parameters:
        - in: body
          name: payload
          required: true
          schema:
            type: object
            properties:
              say_hello:
                type: boolean
      responses:
        200:
          description: Response message
          schema:
            type: object
            properties:
              message:
                type: string
