"""Auto migration

Revision ID: 319ab221b6ec
Revises: f47d1bbee100
Create Date: 2025-08-14 14:13:17.389287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319ab221b6ec'
down_revision: Union[str, Sequence[str], None] = 'f47d1bbee100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('cluster_metrics', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('node_metrics', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('pod_metrics', sa.Column('domain', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pod_metrics', 'domain')
    op.drop_column('node_metrics', 'domain')
    op.drop_column('cluster_metrics', 'domain')
    op.drop_table('providers')
    # ### end Alembic commands ###
