"""Updates of instance table

Revision ID: f10a35456dcb
Revises: 36a50c74f2f8
Create Date: 2025-08-09 08:25:12.836347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10a35456dcb'
down_revision: Union[str, Sequence[str], None] = '36a50c74f2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubernetes_instances', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('kubernetes_instances', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kubernetes_instances', 'password')
    op.drop_column('kubernetes_instances', 'username')
    # ### end Alembic commands ###
