"""Auto migration

Revision ID: f47d1bbee100
Revises: f10a35456dcb
Create Date: 2025-08-09 10:50:24.369369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f47d1bbee100'
down_revision: Union[str, Sequence[str], None] = 'f10a35456dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kubernetes_instances', sa.Column('unique_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'kubernetes_instances', ['unique_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kubernetes_instances', type_='unique')
    op.drop_column('kubernetes_instances', 'unique_hash')
    # ### end Alembic commands ###
